### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by zoccoler** [maleehahassan/napari-my-plugin#1]
Hi Maleeha @maleehahassan ,

I tried to install your plugin, but I got an error. Please see the error below:

    ERROR: Could not find a version that satisfies the requirement napari-my-plugin (from versions: none)
    ERROR: No matching distribution found for napari-my-plugin

Do you know how to fix it?

Best,
Marcelo

**Comment by maleehahassan** [comment]
oh noooooo. I am the worst. I am sorry. I just fixed it.

**Comment by zoccoler** [comment]
Hey, I just tried and it worked! But I cannot open napari. It gives me this message:

    'napari' is not recognized as an internal or external command,
    operable program or batch file.

**Comment by maleehahassan** [comment]
all fixed. Please follow the updated instructions.
